### ISSUE TITLE
Milestone 2 checklist

### ISSUE THREAD

**Issue by renee-kwon** [UBC-MDS/DSCI525_group16#25]
Milestone 2 checklist

- [x] 1. Setup your EC2 instance
- [x] 2. Setup the server
- [x] 3. Setup your JupyterHub
- [x] 4. Get the data what we wrangled in our first milestone.
- [x] 5. Setup your S3 bucket and move data
- [x] 6. Wrangle the data in preparation for machine learning
